### ISSUE TITLE
[Bug]: Wrong HTTP Codes when server has specific errors 

### ISSUE THREAD

**Issue by Sigeth** [AYDEV-FR/ISEN-API#27]
## Short description

The errors being concerned are when ENT is not responding in time (Aurion is down) and when login information is wrong on `/token` endpoint (Bad credentials)

## Expected Behavior

- Aurion is down : Error code 504 Gateway Timeout, which means the server we take the information from is not responding in the given time (10 seconds here)
- Bad credentials : 401 Unauthorized which means the user is not authorized to access any token with the given credentials

## Actual Behavior

- Aurion is down : 500 Internal Server Error
- Bad credentials : 500 Internal Server Error

## Steps to Reproduce the Problem

Aurion is down :
1. Wait Aurion is down
2. Try to use an endpoint other than `/token`

Bad credentials :
1. Enter invented credentials in `/token` endpoint

**Comment by AYDEV-FR** [comment]
Wait Aurion is down, just wait Monday morning 😂
