### ISSUE TITLE
Changing output to camelCase

### ISSUE THREAD

**Issue by Sigeth** [AYDEV-FR/ISEN-API#7]
Idea is based on the convention made by Google : [Google JSON Style Guide](https://google.github.io/styleguide/jsoncstyleguide.xml?showone=Property_Name_Format#Property_Name_Format)
Currently, the API is `PascalCase` and no other APIs are using it (from what I see, it's mostly `camelCase` or `snake_case`)
I think it is better to have `camelCase` as most of the clients will be web apps.

**Comment by AYDEV-FR** [comment]
Hi @Sigeth 
I agree with you. The JSON API return the entries should be in camelCase.
I don't know why I mix different pattern.

I'll let you make a new PR ;)
